app:
  name: currentexchappp
  port: :8080

# database:
#   host: localhost
#   port: 3306
#   user: your_username
#   password: your_password
#   name: current_exchange_db
dsn: host=localhost user=myuser password=mypassword dbname=gorm_db port=5432 sslmode=disable TimeZone=Asia/Shanghai
maxIdleConns: 10
maxOpenConns: 1000
