app:
  name: currentexchappp
  port: :8080

database:
  dsn: host=localhost user=myuser password=mypassword dbname=gorm_db port=5432 sslmode=disable TimeZone=Asia/Shanghai
  maxIdleConns: 10
  maxOpenConns: 1000
